# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_norm_stats": "00_utils.ipynb",
         "draw_rect": "00_utils.ipynb",
         "convert_cords": "00_utils.ipynb",
         "resize": "00_utils.ipynb",
         "noise": "00_utils.ipynb",
         "get_prompt_points": "00_utils.ipynb",
         "PTBDataset": "01_data.ipynb",
         "PTBTransform": "01_data.ipynb",
         "PTBImage": "01_data.ipynb",
         "ConversionDataset": "01_data.ipynb",
         "EfficientLoc": "02_model.ipynb",
         "CIoU": "02_model.ipynb"}

modules = ["utils.py",
           "data.py",
           "model.py",
           "fastai.py",
           "None.py"]

doc_url = "https://BavarianToolbox.github.io/point_to_box/"

git_url = "https://github.com/BavarianToolbox/point_to_box/tree/master/"

def custom_doc_links(name): return None
